name: Update RSS

on:
  schedule:
    - cron: '*/5 * * * *'  # يعمل كل ساعة
  workflow_dispatch:  # يسمح بالتشغيل يدويًا

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    - name: Run script
      run: python generate_rss.py
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add search_rss.xml
        git commit -m "Update RSS" || echo "No changes"
        git push
